export const routes = {
  home: "/",
  games: "/jogos",
  search: "/buscar",
  login: "/login",
  signUp: "/cadastro",
  passwordRecovery: "/recuperar-senha",
  dashboard: "/dashboard",
  settings: "/configuracoes",
  admin: "/admin",
  adminGames: "/admin/jogos",
  adminGameNew: "/admin/jogos/novo",
  adminGame: (gameId: string) => `/admin/jogos/${gameId}`,
  adminGameReleases: (gameId: string) => `/admin/jogos/${gameId}/releases`,
  adminGameContentPacks: (gameId: string) => `/admin/jogos/${gameId}/content-packs`,
  adminGameAchievementSets: (gameId: string) => `/admin/jogos/${gameId}/achievement-sets`,
  adminGameAchievementSet: (gameId: string, achievementSetId: string) =>
    `/admin/jogos/${gameId}/achievement-sets/${achievementSetId}`,
  adminPlatforms: "/admin/plataformas",
  adminMedia: "/admin/media",
  adminMediaAsset: (assetId: string) => `/admin/media/${assetId}`,
} as const;
